name: Windows Build

on:
  workflow_dispatch:

jobs:

  build-windows-x86_64:
    runs-on: windows-latest
    name: Build for Windows x86_64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: mingw-w64-x86_64-gcc

    - name: Install V
      run: |
        curl -L -o v.zip https://github.com/vlang/v/releases/latest/download/v_windows.zip
        tar -xf v.zip
        rm v.zip
        echo "%CD%" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        v version

    - name: Build shared library
      run: |
        if not exist ".\\lib\\windows" mkdir ".\\lib\\windows"
        C:\\msys64\\mingw64\\bin\\gcc -shared .\\core\\php_wasm.v -o .\\lib\\windows\\wasm.dll
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wasm-windows-x86_64
        path: .\lib\windows\wasm.dll
        if-no-files-found: error
